# Generated by Django 6.0.4 on 2026-04-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field name/identifier', max_length=255)),
                ('location', models.CharField(help_text='Field location/region', max_length=255)),
                ('crop_type', models.CharField(help_text='Type of crop being grown', max_length=100)),
                ('planting_date', models.DateField(help_text='Date when crop was planted')),
                ('size_in_acres', models.DecimalField(decimal_places=2, help_text='Size of field in acres', max_digits=8)),
                ('stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], default='planted', help_text='Current stage of crop growth', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('completed', 'Completed')], default='active', help_text='Health/operational status of field', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='General notes about the field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'db_table': 'fields_field',
                'ordering': ['-created_at'],
            },
        ),
    ]
