# Generated by Django 6.0.4 on 2026-04-24 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Field agent responsible for this field', limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='field',
            name='created_by',
            field=models.ForeignKey(help_text='Admin who created this field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['assigned_to', '-created_at'], name='fields_fiel_assigne_b0e195_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['status'], name='fields_fiel_status_368c94_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['stage'], name='fields_fiel_stage_bc3ea7_idx'),
        ),
    ]
