# Generated by Django 6.0.4 on 2026-04-24 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Name of the field that changed (e.g., 'status', 'stage')", max_length=100)),
                ('old_value', models.CharField(blank=True, help_text='Previous value', max_length=255)),
                ('new_value', models.CharField(help_text='New value', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_changes', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(help_text='Field that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='fields.field')),
            ],
            options={
                'verbose_name': 'Field History',
                'verbose_name_plural': 'Field Histories',
                'db_table': 'fields_fieldhistory',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['field', '-changed_at'], name='fields_fiel_field_i_2c7e98_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(help_text='Field this note is about', on_delete=django.db.models.deletion.CASCADE, related_name='field_notes', to='fields.field')),
            ],
            options={
                'verbose_name': 'Field Note',
                'verbose_name_plural': 'Field Notes',
                'db_table': 'fields_fieldnote',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field', '-created_at'], name='fields_fiel_field_i_db3a55_idx')],
            },
        ),
    ]
