# Generated by Django 6.0.4 on 2026-04-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], help_text='Updated stage of the crop', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observations or notes from the agent')),
                ('photos', models.TextField(blank=True, help_text='JSON array of photo URLs or base64 encoded images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field Update',
                'verbose_name_plural': 'Field Updates',
                'db_table': 'updates_fieldupdate',
                'ordering': ['-created_at'],
            },
        ),
    ]
