# Generated by Django 6.0.4 on 2026-04-24 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0002_initial'),
        ('updates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldupdate',
            name='agent',
            field=models.ForeignKey(help_text='Agent who submitted the update', limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldupdate',
            name='field',
            field=models.ForeignKey(help_text='Field being updated', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='fields.field'),
        ),
        migrations.AddIndex(
            model_name='fieldupdate',
            index=models.Index(fields=['field', '-created_at'], name='updates_fie_field_i_c4953f_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldupdate',
            index=models.Index(fields=['agent', '-created_at'], name='updates_fie_agent_i_3a4c76_idx'),
        ),
    ]
